import { describe, it, expect } from "vitest";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import * as fs from "node:fs";
import * as os from "node:os";
import { spawnSync } from "node:child_process";
import { claudeConverter } from "../src/converters/claude.js";
import { opencodeConverter } from "../src/converters/opencode.js";
import { cursorConverter } from "../src/converters/cursor.js";
import { windsurfConverter } from "../src/converters/windsurf.js";
import { copilotConverter } from "../src/converters/copilot.js";
import { codexConverter } from "../src/converters/codex.js";
import type { Capability, Converter } from "../src/converters/types.js";
import { renderCliMatrix, renderReadmeMatrix, syncReadme } from "../src/matrix.js";
import type { Feature, FidelityItem, HarnessConfig } from "../src/schema.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));

// Mirrors features/capability-declaration.feature and features/conversion-reporting.feature,
// generated by openspec-bdd from openspec/changes/capability-matrix/specs/.

const CONVERTERS: Record<string, Converter> = {
  claude: claudeConverter,
  opencode: opencodeConverter,
  cursor: cursorConverter,
  windsurf: windsurfConverter,
  copilot: copilotConverter,
  codex: codexConverter,
};

const FEATURES: Feature[] = [
  "rule", "agent", "skill", "command",
  "mcp", "permission", "hook", "formatter",
];

const CAPABILITIES: Capability[] = ["full", "user-level", "none"];

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "harnessport-cap-"));
}

/** A config holding one of every feature, so every converter has something to report on. */
function everyFeature(): HarnessConfig {
  return {
    rules: [{ content: "Be careful.", source: "rules.md" }],
    agents: [{ name: "reviewer", body: "Review it.", description: "Reviews code" }],
    skills: [{ name: "testing", body: "Test it." }],
    commands: [{ name: "ship", body: "Ship it." }],
    mcpServers: [{ name: "fs", type: "stdio", command: "npx", args: ["mcp-fs"] }],
    permissions: [{ tool: "bash", pattern: "npm run:*", action: "allow" }],
    hooks: [{ event: "PreToolUse", matcher: "Bash", command: "./guard.sh" }],
    formatters: [{ glob: "*.py", command: "ruff format" }],
    items: [],
  };
}

/** Export to a real directory — dry runs never execute the serialization path. */
function exportEveryFeature(converter: Converter): FidelityItem[] {
  return converter.export(tmpDir(), everyFeature(), {}).items;
}

function itemsOfKind(items: FidelityItem[], kind: Feature): FidelityItem[] {
  return items.filter((i) => i.kind === kind);
}

describe("Requirement: Every converter declares what it converts", () => {
  it.each(Object.keys(CONVERTERS))("%s declares every feature", (name) => {
    const declared = CONVERTERS[name].capabilities;
    for (const feature of FEATURES) {
      expect(CAPABILITIES).toContain(declared[feature]);
    }
  });

  it.each([
    ["cursor", "agent", "full"],
    ["cursor", "skill", "full"],
    ["cursor", "command", "full"],
    ["cursor", "mcp", "full"],
    ["copilot", "agent", "full"],
    ["copilot", "skill", "full"],
    ["copilot", "command", "full"],
    ["copilot", "mcp", "full"],
    ["copilot", "hook", "full"],
    ["windsurf", "agent", "none"],
    ["windsurf", "mcp", "user-level"],
    ["windsurf", "command", "full"],
    ["codex", "agent", "user-level"],
    ["codex", "mcp", "user-level"],
    ["codex", "command", "none"],
    ["codex", "hook", "full"],
    ["codex", "permission", "none"],
    ["opencode", "hook", "none"],
    ["opencode", "formatter", "full"],
    ["claude", "permission", "full"],
    ["claude", "formatter", "full"],
  ] as Array<[string, Feature, Capability]>)(
    "%s declares %s as %s",
    (tool, feature, value) => {
      expect(CONVERTERS[tool].capabilities[feature]).toBe(value);
    },
  );
});

describe("Requirement: A declaration disagreeing with export behaviour fails the build", () => {
  it.each([
    ["claude", "agent"],
    ["claude", "hook"],
    ["claude", "formatter"],
    ["opencode", "agent"],
    ["opencode", "formatter"],
    ["cursor", "agent"],
    ["copilot", "hook"],
    ["codex", "hook"],
  ] as Array<[string, Feature]>)(
    "%s represents %s in the output, as declared full",
    (tool, feature) => {
      const items = itemsOfKind(exportEveryFeature(CONVERTERS[tool]), feature);
      expect(items.some((i) => i.status === "exact" || i.status === "lossy")).toBe(true);
    },
  );

  it.each([
    ["windsurf", "agent"],
    ["windsurf", "mcp"],
    ["windsurf", "hook"],
    ["cursor", "permission"],
    ["cursor", "hook"],
    ["cursor", "formatter"],
    ["copilot", "permission"],
    ["copilot", "formatter"],
    ["codex", "agent"],
    ["codex", "command"],
    ["codex", "mcp"],
    ["opencode", "hook"],
  ] as Array<[string, Feature]>)(
    "%s never reports %s as written, as declared unconverted",
    (tool, feature) => {
      const items = itemsOfKind(exportEveryFeature(CONVERTERS[tool]), feature);
      expect(items.length).toBeGreaterThan(0);
      expect(items.every((i) => i.status === "dropped" || i.status === "blocked")).toBe(true);
    },
  );

  // The declaration is checked against behaviour for every cell, not only the named ones above.
  it.each(Object.keys(CONVERTERS))("%s agrees with its own export for all eight features", (name) => {
    const converter = CONVERTERS[name];
    const items = exportEveryFeature(converter);
    for (const feature of FEATURES) {
      const kindItems = itemsOfKind(items, feature);
      const written = kindItems.some((i) => i.status === "exact" || i.status === "lossy");
      expect({ feature, written }).toEqual({
        feature,
        written: converter.capabilities[feature] === "full",
      });
    }
  });
});

describe("Requirement: A user-level declaration names the path it lives at", () => {
  it("Windsurf MCP names the user-level config file", () => {
    const [item] = itemsOfKind(exportEveryFeature(windsurfConverter), "mcp");
    expect(item.reason).toContain("~/.codeium/windsurf/mcp_config.json");
  });

  it("Codex agents name the user-level config file", () => {
    const items = itemsOfKind(exportEveryFeature(codexConverter), "agent");
    expect(items.some((i) => i.reason?.includes("~/.codex/config.toml"))).toBe(true);
  });
});

describe("Requirement: The list command renders from the declaration", () => {
  const cli = renderCliMatrix();

  function cell(feature: string, tool: string): string {
    const header = cli.split("\n").find((l) => l.includes("Claude"));
    const row = cli.split("\n").find((l) => l.startsWith(feature));
    expect(header).toBeDefined();
    expect(row).toBeDefined();
    const columns = (header as string).split("|").map((c) => c.trim().toLowerCase());
    const index = columns.findIndex((c) => c.startsWith(tool.slice(0, 6)));
    expect(index).toBeGreaterThan(0);
    return (row as string).split("|")[index].trim();
  }

  it.each([
    ["cursor", "Agents", "✓"],
    ["cursor", "Skills", "✓"],
    ["cursor", "Commands", "✓"],
    ["copilot", "Agents", "✓"],
    ["copilot", "Skills", "✓"],
    ["copilot", "Commands", "✓"],
    ["copilot", "MCP Servers", "✓"],
    ["copilot", "Hooks", "✓"],
    ["windsurf", "MCP Servers", "~"],
    ["windsurf", "Agents", "-"],
    ["codex", "Agents", "~"],
    ["codex", "Permissions", "-"],
  ])("%s shows %s as %s", (tool, feature, symbol) => {
    expect(cell(feature, tool)).toBe(symbol);
  });

  it("The legend defines all three symbols", () => {
    expect(cli).toContain("✓ =");
    expect(cli).toContain("~ =");
    expect(cli).toContain("- =");
  });

  const CLI_PATH = path.resolve(HERE, "..", "dist", "index.js");
  it.runIf(fs.existsSync(CLI_PATH))("The built CLI prints the rendered matrix", () => {
    const r = spawnSync("node", [CLI_PATH, "list"], { encoding: "utf-8" });
    expect(r.status).toBe(0);
    expect(r.stdout).toContain(renderCliMatrix());
  });
});

describe("Requirement: The README matrix is generated and drift fails the check", () => {
  const README = path.resolve(HERE, "..", "README.md");

  it("A matching README passes the check", () => {
    expect(syncReadme(README, { check: true }).drifted).toBe(false);
  });

  it("An edited README fails the check", () => {
    const dir = tmpDir();
    const copy = path.join(dir, "README.md");
    fs.writeFileSync(
      copy,
      fs.readFileSync(README, "utf-8").replace("| Cursor ", "| Kursor "),
    );
    const outcome = syncReadme(copy, { check: true });
    expect(outcome.drifted).toBe(true);
    expect(outcome.message).toContain("npm run docs:matrix");
  });

  it("Regeneration is idempotent", () => {
    const dir = tmpDir();
    const copy = path.join(dir, "README.md");
    fs.copyFileSync(README, copy);
    const before = fs.readFileSync(copy, "utf-8");
    syncReadme(copy, { check: false });
    expect(fs.readFileSync(copy, "utf-8")).toBe(before);
  });

  it("The generated region is what the declaration renders", () => {
    expect(fs.readFileSync(README, "utf-8")).toContain(renderReadmeMatrix());
  });
});

describe("Requirement: A hook OpenCode cannot run is reported dropped", () => {
  it("A claude PreToolUse hook exported to opencode is dropped", () => {
    const [item] = itemsOfKind(exportEveryFeature(opencodeConverter), "hook");
    expect(item.name).toBe("PreToolUse");
    expect(item.status).toBe("dropped");
    expect(item.reason).toMatch(/formatters/i);
  });

  it("A dropped hook does not fail the run", () => {
    const items = exportEveryFeature(opencodeConverter);
    expect(items.filter((i) => i.status === "blocked")).toHaveLength(0);
  });

  it("Formatters are still converted", () => {
    const dir = tmpDir();
    const result = opencodeConverter.export(dir, everyFeature(), {});
    const emitted = JSON.parse(
      fs.readFileSync(path.join(dir, "opencode.json"), "utf-8"),
    ) as { formatter?: Record<string, unknown> };
    expect(emitted.formatter).toBeDefined();
    expect(
      itemsOfKind(result.items, "formatter").every((i) => i.status === "exact"),
    ).toBe(true);
  });
});
