import { describe, it, expect } from "vitest";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import * as fs from "node:fs";
import * as os from "node:os";
import { claudeConverter } from "../src/converters/claude.js";
import { cursorConverter } from "../src/converters/cursor.js";
import { copilotConverter } from "../src/converters/copilot.js";
import type { HarnessConfig } from "../src/schema.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));

// Mirrors features/claude-rule-scoping.feature, generated by openspec-bdd from
// openspec/changes/claude-rule-scoping/specs/.

const SAMPLE = path.resolve(HERE, "fixtures", "sample-project");

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "harnessport-cr-"));
}

function write(dir: string, rel: string, content: string): void {
  const p = path.join(dir, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
}

function configWith(rules: HarnessConfig["rules"]): HarnessConfig {
  return {
    rules, agents: [], skills: [], commands: [],
    mcpServers: [], permissions: [], hooks: [], formatters: [], items: [],
  };
}

/** Read every emitted file back, keyed by path relative to the export root. */
function readTree(dir: string): Record<string, string> {
  const out: Record<string, string> = {};
  const walk = (d: string) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else out[path.relative(dir, p)] = fs.readFileSync(p, "utf-8");
    }
  };
  walk(dir);
  return out;
}

describe("Requirement: Every documented Claude instruction location is read", () => {
  it("A root CLAUDE.md is found", () => {
    const dir = tmpDir();
    write(dir, "CLAUDE.md", "# Root rules\n");
    expect(claudeConverter.detect(dir)).toBe(true);
  });

  it("A root CLAUDE.md is imported", () => {
    const dir = tmpDir();
    write(dir, "CLAUDE.md", "# Root rules\n\nBe careful.");
    const config = claudeConverter.import(dir);
    expect(config.rules.some((r) => r.content.includes("Be careful"))).toBe(true);
  });

  it("Both instruction locations are read together", () => {
    const dir = tmpDir();
    write(dir, "CLAUDE.md", "# Root\n");
    write(dir, ".claude/CLAUDE.md", "# Nested\n");
    expect(claudeConverter.import(dir).rules).toHaveLength(2);
  });

  it("A local instruction file is imported", () => {
    const dir = tmpDir();
    write(dir, "CLAUDE.local.md", "# Personal\n\nMy sandbox URL.");
    const config = claudeConverter.import(dir);
    expect(config.rules.some((r) => r.content.includes("My sandbox URL"))).toBe(true);
  });

  it.each([
    [".claude/skills"],
    [".claude/agents"],
    [".claude/commands"],
    [".claude/rules"],
  ])("A repository is detected by %s alone", (dir) => {
    const root = tmpDir();
    fs.mkdirSync(path.join(root, dir), { recursive: true });
    expect(claudeConverter.detect(root)).toBe(true);
  });
});

describe("Requirement: File-scoped rules keep their scope", () => {
  it("paths frontmatter imports as globs", () => {
    const dir = tmpDir();
    write(dir, ".claude/rules/api.md", "---\npaths:\n  - src/api/**/*.ts\n---\n\nValidate input.");
    const config = claudeConverter.import(dir);
    const rule = config.rules.find((r) => r.content.includes("Validate input"));
    expect(rule?.globs).toContain("src/api/**/*.ts");
  });

  it("A glob-scoped rule exports to .claude/rules", () => {
    const dir = tmpDir();
    claudeConverter.export(
      dir,
      configWith([{ content: "TS rules", globs: "src/**/*.ts", source: "typescript.mdc" }]),
      {},
    );
    const emitted = fs.readFileSync(path.join(dir, ".claude", "rules", "typescript.md"), "utf-8");
    expect(emitted).toContain("src/**/*.ts");
    expect(emitted).toContain("paths");
    expect(emitted).toContain("TS rules");
  });

  it("An unscoped rule stays in the instructions file", () => {
    const dir = tmpDir();
    claudeConverter.export(dir, configWith([{ content: "Global rules" }]), {});
    expect(fs.existsSync(path.join(dir, ".claude", "rules"))).toBe(false);
    expect(
      fs.readFileSync(path.join(dir, ".claude", "CLAUDE.md"), "utf-8"),
    ).toContain("Global rules");
  });

  it("Multiple globs survive as a list", () => {
    const dir = tmpDir();
    claudeConverter.export(
      dir,
      configWith([{ content: "x", globs: "src/**/*.ts,lib/**/*.ts", source: "ts.md" }]),
      {},
    );
    const emitted = fs.readFileSync(path.join(dir, ".claude", "rules", "ts.md"), "utf-8");
    expect(emitted).toContain("src/**/*.ts");
    expect(emitted).toContain("lib/**/*.ts");
  });

  it("Cursor glob scoping survives a round trip through claude", () => {
    const cursorSrc = tmpDir();
    write(
      cursorSrc,
      ".cursor/rules/typescript.mdc",
      "---\ndescription: ''\nglobs: src/**/*.ts\nalwaysApply: false\n---\n\nUse strict mode.",
    );

    const claudeDir = tmpDir();
    claudeConverter.export(claudeDir, cursorConverter.import(cursorSrc), {});

    const backDir = tmpDir();
    cursorConverter.export(backDir, claudeConverter.import(claudeDir), {});

    const roundTripped = cursorConverter.import(backDir);
    const rule = roundTripped.rules.find((r) => r.content.includes("Use strict mode"));
    expect(rule?.globs).toBe("src/**/*.ts");
  });

  it("Claude paths scoping survives a round trip through copilot", () => {
    const claudeSrc = tmpDir();
    write(claudeSrc, ".claude/rules/api.md", "---\npaths:\n  - src/api/**/*.ts\n---\n\nAPI rules.");

    const copilotDir = tmpDir();
    copilotConverter.export(copilotDir, claudeConverter.import(claudeSrc), {});

    const backDir = tmpDir();
    claudeConverter.export(backDir, copilotConverter.import(copilotDir), {});

    const rule = claudeConverter
      .import(backDir)
      .rules.find((r) => r.content.includes("API rules"));
    expect(rule?.globs).toContain("src/api/**/*.ts");
  });

  it("A scoped rule is reported exact rather than lossy", () => {
    const dir = tmpDir();
    const result = claudeConverter.export(
      dir,
      configWith([{ content: "x", globs: "src/**/*.ts", source: "ts.md" }]),
      {},
    );
    const ruleItems = result.items.filter((i) => i.kind === "rule" && i.name.includes("ts"));
    expect(ruleItems.every((i) => i.status === "exact")).toBe(true);
  });
});

describe("Requirement: The instructions file does not duplicate an existing one", () => {
  it("An existing root file is the target", () => {
    const dir = tmpDir();
    write(dir, "CLAUDE.md", "# Existing root\n");
    claudeConverter.export(dir, configWith([{ content: "New rules" }]), { force: true });
    expect(fs.existsSync(path.join(dir, ".claude", "CLAUDE.md"))).toBe(false);
  });

  it("A clean target uses the .claude directory", () => {
    const dir = tmpDir();
    claudeConverter.export(dir, configWith([{ content: "New rules" }]), {});
    expect(fs.existsSync(path.join(dir, ".claude", "CLAUDE.md"))).toBe(true);
    expect(fs.existsSync(path.join(dir, "CLAUDE.md"))).toBe(false);
  });
});

describe("Requirement: Scoping that cannot be represented is reported precisely", () => {
  it("A description-activated rule is reported lossy", () => {
    const dir = tmpDir();
    const result = claudeConverter.export(
      dir,
      configWith([{ content: "x", description: "Apply when reviewing", source: "review.md" }]),
      {},
    );
    const item = result.items.find((i) => i.kind === "rule" && i.name.includes("review"));
    expect(item?.status).toBe("lossy");
    expect(item?.reason).toMatch(/description/i);
  });

  it("A plain rule is reported exact", () => {
    const dir = tmpDir();
    const result = claudeConverter.export(dir, configWith([{ content: "x", source: "plain.md" }]), {});
    const item = result.items.find((i) => i.kind === "rule" && i.name.includes("plain"));
    expect(item?.status).toBe("exact");
  });
});

describe("Regression: existing behaviour is preserved", () => {
  it("The sample fixture still imports exactly one rule", () => {
    expect(claudeConverter.import(SAMPLE).rules).toHaveLength(1);
  });

  it("A glob-free config emits the same tree as before", () => {
    const dir = tmpDir();
    claudeConverter.export(dir, claudeConverter.import(SAMPLE), {});
    const tree = readTree(dir);
    expect(Object.keys(tree)).toContain(path.join(".claude", "CLAUDE.md"));
    expect(Object.keys(tree).some((f) => f.includes(`rules${path.sep}`))).toBe(false);
  });
});
