import { describe, it, expect } from "vitest";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import * as fs from "node:fs";
import * as os from "node:os";
import { spawnSync } from "node:child_process";
import { claudeConverter } from "../src/converters/claude.js";
import { opencodeConverter } from "../src/converters/opencode.js";
import { cursorConverter } from "../src/converters/cursor.js";
import { windsurfConverter } from "../src/converters/windsurf.js";
import { copilotConverter } from "../src/converters/copilot.js";
import { codexConverter } from "../src/converters/codex.js";
import type { Converter } from "../src/converters/types.js";
import type { HarnessConfig, PermissionEntry } from "../src/schema.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));

// Mirrors features/permission-fidelity.feature and features/conversion-reporting.feature,
// generated by openspec-bdd from openspec/changes/fidelity-core/specs/.
// The .feature files are the spec of record; these are their executable form, because this
// repo's gate is vitest rather than cucumber-js.

const FIXTURES = path.resolve(HERE, "fixtures");
const SAMPLE = path.join(FIXTURES, "sample-project");
const OPENCODE_DENY = path.join(FIXTURES, "opencode-deny");
const CLAUDE_DENY = path.join(FIXTURES, "claude-deny");

const TARGETS: Record<string, Converter> = {
  claude: claudeConverter,
  opencode: opencodeConverter,
  cursor: cursorConverter,
  windsurf: windsurfConverter,
  copilot: copilotConverter,
  codex: codexConverter,
};

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "harnessport-"));
}

/** Export to a real directory and read every emitted file back. */
function exportToDisk(converter: Converter, config: HarnessConfig) {
  const dir = tmpDir();
  const result = converter.export(dir, config, {});
  const contents = result.filesWritten.map((f) =>
    fs.existsSync(f) ? fs.readFileSync(f, "utf-8") : "",
  );
  return { dir, result, contents, joined: contents.join("\n") };
}

function permission(
  tool: string,
  pattern: string,
  action: "allow" | "ask" | "deny",
): PermissionEntry {
  return { tool, pattern, action } as PermissionEntry;
}

function configWith(permissions: PermissionEntry[]): HarnessConfig {
  return {
    rules: [{ content: "# Rules\n\nBe careful.", source: "CLAUDE.md" }],
    agents: [],
    skills: [],
    commands: [],
    mcpServers: [],
    permissions,
    hooks: [],
    formatters: [],
    items: [],
  } as unknown as HarnessConfig;
}

// ---------------------------------------------------------------------------
// Feature: permission-fidelity
// ---------------------------------------------------------------------------

describe("Requirement: Permission entries carry an action", () => {
  it("OpenCode deny survives import", () => {
    const config = opencodeConverter.import(OPENCODE_DENY);
    // OpenCode's config key is `bash`; the canonical tool name is `Bash`, which is what the
    // targets match on. Importing the lowercase key verbatim produced entries Claude Code
    // ignored — see tests/permission-names.test.ts.
    const entry = config.permissions.find(
      (p) => p.tool === "Bash" && p.pattern === "rm -rf *",
    );
    expect(entry).toBeDefined();
    expect(entry?.action).toBe("deny");
  });

  it("Claude deny list is imported", () => {
    const config = claudeConverter.import(CLAUDE_DENY);
    const entry = config.permissions.find(
      (p) => p.tool === "Bash" && p.pattern === "curl *",
    );
    expect(entry).toBeDefined();
    expect(entry?.action).toBe("deny");
  });

  it("Claude permissions are read from both settings files", () => {
    const config = claudeConverter.import(CLAUDE_DENY);
    const fromProject = config.permissions.find((p) => p.pattern === "npm test");
    const fromLocal = config.permissions.find((p) => p.pattern === "./.env");
    expect(fromProject?.action).toBe("allow");
    expect(fromLocal?.action).toBe("deny");
  });

  it("An action-less source defaults to allow", () => {
    const config = claudeConverter.import(SAMPLE);
    expect(config.permissions.length).toBeGreaterThan(0);
    expect(config.permissions.every((p) => p.action === "allow")).toBe(true);
  });

  it.each([
    ["allow", "allow"],
    ["ask", "ask"],
    ["deny", "deny"],
  ])("Each action maps to its matching Claude settings key: %s -> %s", (action, key) => {
    const config = configWith([
      permission("Bash", "ls *", action as "allow" | "ask" | "deny"),
    ]);
    const { dir } = exportToDisk(claudeConverter, config);
    const settings = JSON.parse(
      fs.readFileSync(path.join(dir, ".claude", "settings.local.json"), "utf-8"),
    );
    expect(settings.permissions[key]).toContain("Bash(ls *)");
  });
});

describe("Requirement: A conversion never weakens a permission posture", () => {
  it("A deny bound for a target with no permission model is refused, not downgraded", () => {
    const config = configWith([permission("Bash", "rm -rf *", "deny")]);
    const { result, joined } = exportToDisk(cursorConverter, config);
    const blocked = result.items.filter((i) => i.status === "blocked");
    expect(blocked.length).toBe(1);
    expect(blocked[0].name).toContain("rm -rf *");
    expect(joined).not.toContain("rm -rf *");
  });

  it("The rest of the conversion still completes", () => {
    const config = configWith([permission("Bash", "rm -rf *", "deny")]);
    config.agents = [{ name: "a", body: "agent body" }];
    config.skills = [{ name: "s", body: "skill body" }];
    config.commands = [{ name: "c", body: "command body" }];

    const { result } = exportToDisk(cursorConverter, config);
    expect(result.filesWritten.some((f) => f.includes("/rules/"))).toBe(true);
    expect(result.filesWritten.some((f) => f.includes("/agents/"))).toBe(true);
    expect(result.filesWritten.some((f) => f.includes("SKILL.md"))).toBe(true);
    expect(result.filesWritten.some((f) => f.includes("/commands/"))).toBe(true);
    expect(result.items.filter((i) => i.status === "blocked").length).toBe(1);
  });

  it.each([
    ["claude", "exact"],
    ["opencode", "exact"],
    ["cursor", "blocked"],
    ["windsurf", "blocked"],
    ["copilot", "blocked"],
    ["codex", "blocked"],
  ])("A deny is refused for every target that cannot represent it: %s -> %s", (target, status) => {
    const config = configWith([permission("Bash", "rm -rf *", "deny")]);
    const { result } = exportToDisk(TARGETS[target], config);
    const permItems = result.items.filter((i) => i.kind === "permission");
    expect(permItems.length).toBeGreaterThan(0);
    expect(permItems.every((i) => i.status === status)).toBe(true);
  });
});

describe("Requirement: OpenCode shorthand-only tools do not silently widen a deny", () => {
  it("A shorthand-only tool holding a deny is refused", () => {
    const config = configWith([permission("webfetch", "https://x.example.com/*", "deny")]);
    const { dir, result } = exportToDisk(opencodeConverter, config);
    const blocked = result.items.filter((i) => i.status === "blocked");
    expect(blocked.length).toBeGreaterThan(0);
    expect(blocked.some((i) => i.name.includes("webfetch"))).toBe(true);

    const json = JSON.parse(fs.readFileSync(path.join(dir, "opencode.json"), "utf-8"));
    expect(json.permission?.webfetch).not.toBe("allow");
  });

  it("A granular tool keeps its per-pattern deny", () => {
    const config = configWith([permission("bash", "rm -rf *", "deny")]);
    const { dir, result } = exportToDisk(opencodeConverter, config);
    const json = JSON.parse(fs.readFileSync(path.join(dir, "opencode.json"), "utf-8"));
    expect(json.permission.bash["rm -rf *"]).toBe("deny");
    expect(
      result.items.filter((i) => i.kind === "permission").every((i) => i.status === "exact"),
    ).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Feature: conversion-reporting
// ---------------------------------------------------------------------------

describe("Requirement: Conversion fidelity is reported per item", () => {
  it("A feature the target cannot represent is reported per item", () => {
    const config = claudeConverter.import(SAMPLE);
    const { result } = exportToDisk(windsurfConverter, config);
    const agentItems = result.items.filter((i) => i.kind === "agent");
    expect(agentItems.length).toBe(2);
    expect(agentItems.map((i) => i.name).sort()).toEqual(["backend", "reviewer"]);
  });

  it("Import-side loss enters the same report", () => {
    const config = codexConverter.import(SAMPLE);
    const importItems = config.items.filter((i) => i.phase === "import");
    expect(importItems.length).toBeGreaterThan(0);
    expect(importItems.some((i) => i.reason?.includes("config.toml"))).toBe(true);
  });

  it("A non-exact item always explains itself", () => {
    const config = claudeConverter.import(SAMPLE);
    for (const name of Object.keys(TARGETS)) {
      if (name === "claude") continue;
      const { result } = exportToDisk(TARGETS[name], config);
      for (const item of result.items) {
        if (item.status !== "exact") {
          expect(item.reason, `${name}/${item.kind}/${item.name}`).toBeTruthy();
        }
      }
    }
  });

  it("A fully representable feature is reported exact", () => {
    const config = claudeConverter.import(SAMPLE);
    const { result } = exportToDisk(opencodeConverter, config);
    const skillItems = result.items.filter((i) => i.kind === "skill");
    expect(skillItems.length).toBe(1);
    expect(skillItems[0].status).toBe("exact");
  });
});

describe("Requirement: A reported outcome matches what was written", () => {
  it("Agents reported as carried over are present in an emitted file", () => {
    const config = claudeConverter.import(SAMPLE);
    const { result, joined } = exportToDisk(windsurfConverter, config);
    const agentItems = result.items.filter((i) => i.kind === "agent");

    const allDropped = agentItems.every((i) => i.status === "dropped");
    const bodiesPresent =
      joined.includes("backend development specialist") && joined.includes("You are a code reviewer");
    expect(allDropped || bodiesPresent).toBe(true);
  });

  it("Codex agent reporting matches its emitted output", () => {
    const config = claudeConverter.import(SAMPLE);
    const { result, joined } = exportToDisk(codexConverter, config);
    const agentItems = result.items.filter((i) => i.kind === "agent");

    const allDropped = agentItems.every((i) => i.status === "dropped");
    const bodiesPresent =
      joined.includes("backend development specialist") && joined.includes("You are a code reviewer");
    expect(allDropped || bodiesPresent).toBe(true);
  });

  // The audit's H2: both exporters claimed agents were "merged" while writing nothing.
  it("No reason claims a merge that did not happen", () => {
    const config = claudeConverter.import(SAMPLE);
    for (const converter of [windsurfConverter, codexConverter]) {
      const { result, joined } = exportToDisk(converter, config);
      const bodiesPresent = joined.includes("backend development specialist");
      for (const item of result.items) {
        if (/merged into/i.test(item.reason ?? "")) {
          expect(bodiesPresent, `${converter.name} claims a merge that did not happen`).toBe(true);
        }
      }
    }
  });
});

describe("Requirement: Exit codes distinguish refusal from ordinary loss", () => {
  it("A conversion that only drops unsupported concepts has nothing blocked", () => {
    const config = claudeConverter.import(SAMPLE);
    const { result } = exportToDisk(windsurfConverter, config);
    expect(result.items.filter((i) => i.status === "blocked")).toHaveLength(0);
    expect(result.items.some((i) => i.status === "dropped")).toBe(true);
  });
});

// Exercises the built CLI, because exit codes and stream routing only exist there.
describe("Requirement: The item list is available as JSON", () => {
  const CLI = path.resolve(HERE, "..", "dist", "index.js");
  const hasBuild = fs.existsSync(CLI);

  function run(args: string[]) {
    const r = spawnSync("node", [CLI, ...args], { encoding: "utf-8" });
    return { status: r.status, stdout: r.stdout, stderr: r.stderr };
  }

  it.runIf(hasBuild)("JSON output parses and carries every item", () => {
    const r = run([
      "convert", "--from", "opencode", "--to", "cursor",
      "--source", OPENCODE_DENY, "--target", tmpDir(), "--dry-run", "--json",
    ]);
    const parsed = JSON.parse(r.stdout);
    expect(Array.isArray(parsed.items)).toBe(true);
    for (const item of parsed.items) {
      expect(item).toHaveProperty("phase");
      expect(item).toHaveProperty("kind");
      expect(item).toHaveProperty("name");
      expect(item).toHaveProperty("status");
    }
  });

  it.runIf(hasBuild)("Exit code accompanies JSON output", () => {
    const r = run([
      "convert", "--from", "opencode", "--to", "cursor",
      "--source", OPENCODE_DENY, "--target", tmpDir(), "--dry-run", "--json",
    ]);
    expect(() => JSON.parse(r.stdout)).not.toThrow();
    expect(r.status).toBe(2);
  });

  it.runIf(hasBuild)("A lossy conversion exits 0", () => {
    const r = run([
      "convert", "--from", "claude", "--to", "windsurf",
      "--source", SAMPLE, "--target", tmpDir(), "--dry-run",
    ]);
    expect(r.status).toBe(0);
  });

  it.runIf(hasBuild)("Existing failure modes keep exit 1", () => {
    const target = tmpDir();
    expect(run(["convert", "--from", "nope", "--to", "claude", "--source", SAMPLE, "--target", target]).status).toBe(1);
    expect(run(["convert", "--from", "claude", "--to", "nope", "--source", SAMPLE, "--target", target]).status).toBe(1);
    expect(run(["convert", "--from", "claude", "--to", "claude", "--source", SAMPLE, "--target", target]).status).toBe(1);
    expect(run(["convert", "--from", "claude", "--to", "cursor", "--source", target, "--target", target]).status).toBe(1);
  });

  it.runIf(hasBuild)("Version matches package.json", () => {
    const pkg = JSON.parse(fs.readFileSync(path.resolve(HERE, "..", "package.json"), "utf-8"));
    expect(run(["--version"]).stdout.trim()).toBe(pkg.version);
  });
});
