import { describe, it, expect } from "vitest";
import * as path from "node:path";
import * as fs from "node:fs";
import * as os from "node:os";
import { fileURLToPath } from "node:url";
import { ALL_CONVERTERS, CONVERTERS } from "../src/matrix.js";
import { roundTripLoss } from "../src/compare.js";
import type { Converter } from "../src/converters/types.js";
import type { FidelityItem } from "../src/schema.js";

// Mirrors features/conversion-matrix.feature, generated by openspec-bdd from
// openspec/changes/conversion-matrix/specs/.
//
// The suite this replaces exercised one importer and five exporters, every one with dryRun:true —
// so five importers and the entire serialization path never ran, and a block named "round-trip"
// performed no export and no re-import.

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.join(HERE, "fixtures");

/** The project fixture standing in for each harness as a conversion source. */
const FIXTURE_DIRS: Record<string, string> = {
  claude: "sample-project",
  opencode: "opencode-project",
  cursor: "cursor-project",
  windsurf: "windsurf-project",
  copilot: "copilot-project",
  codex: "codex-project",
};

const NAMES = ALL_CONVERTERS.map((c) => c.name);

/** Every ordered pair of distinct harnesses — the 30 real conversion paths. */
const PAIRS: Array<[string, string]> = NAMES.flatMap((from) =>
  NAMES.filter((to) => to !== from).map((to): [string, string] => [from, to]),
);

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "harnessport-matrix-"));
}

function fixtureFor(name: string): string {
  return path.join(FIXTURES, FIXTURE_DIRS[name]);
}

/**
 * Import a fixture, export it to a real directory, and re-import with the target.
 * Dry runs never execute serialization, which is why every assertion here writes files.
 */
function convert(from: Converter, to: Converter) {
  const source = from.import(fixtureFor(from.name));
  const dir = tmpDir();
  const result = to.export(dir, source, {});
  return { source, dir, result, target: to.import(dir) };
}

function blockedNames(items: FidelityItem[]): string[] {
  return items.filter((i) => i.status === "blocked").map((i) => i.name).sort();
}

describe("Requirement: Each importer reads its own fixture", () => {
  it.each(NAMES)("%s detects and imports its fixture", (name) => {
    const converter = CONVERTERS[name];
    const dir = fixtureFor(name);
    expect(converter.detect(dir)).toBe(true);
    const config = converter.import(dir);
    expect(config.rules.length).toBeGreaterThan(0);
    expect(config.skills.length).toBeGreaterThan(0);
  });
});

describe("Requirement: Every ordered pair of harnesses converts end to end", () => {
  it("covers all thirty ordered pairs", () => {
    expect(PAIRS).toHaveLength(30);
  });

  it.each(PAIRS)("%s -> %s is detected by its target", (from, to) => {
    const { dir } = convert(CONVERTERS[from], CONVERTERS[to]);
    expect(CONVERTERS[to].detect(dir)).toBe(true);
  });
});

describe("Requirement: Rule text and skill names survive every pair", () => {
  it.each(PAIRS)("%s -> %s keeps rule text", (from, to) => {
    const { source, target } = convert(CONVERTERS[from], CONVERTERS[to]);
    const joined = target.rules.map((r) => r.content).join("\n");
    for (const rule of source.rules) {
      expect(joined).toContain(rule.content.trim().split("\n")[0]);
    }
  });

  it.each(PAIRS)("%s -> %s keeps skill names", (from, to) => {
    const { source, target } = convert(CONVERTERS[from], CONVERTERS[to]);
    for (const skill of source.skills) {
      expect(target.skills.map((s) => s.name)).toContain(skill.name);
    }
  });
});

describe("Requirement: Re-running a conversion changes nothing", () => {
  it.each(PAIRS)("%s -> %s is idempotent", (from, to) => {
    const converter = CONVERTERS[to];
    const source = CONVERTERS[from].import(fixtureFor(from));
    const dir = tmpDir();
    const first = converter.export(dir, source, {});
    const second = converter.export(dir, source, {});
    expect(blockedNames(second.items)).toEqual(blockedNames(first.items));
  });
});

describe("Requirement: Anything lost is accounted for", () => {
  // The comparison lives in src/compare.ts, which `harnessport verify` also uses — so the command
  // and this test cannot disagree about what counts as loss.
  it.each(PAIRS)("%s -> %s explains every loss", (from, to) => {
    const { source, result, target } = convert(CONVERTERS[from], CONVERTERS[to]);
    expect(roundTripLoss(source, target, result.items).unaccounted).toEqual([]);
  });
});
