import { describe, it, expect } from "vitest";
import * as path from "node:path";
import * as fs from "node:fs";
import * as os from "node:os";
import { fileURLToPath } from "node:url";
import { claudeConverter } from "../src/converters/claude.js";
import { opencodeConverter } from "../src/converters/opencode.js";
import type { HarnessConfig, PermissionAction } from "../src/schema.js";

// Mirrors features/permission-fidelity.feature and features/conversion-reporting.feature,
// generated by openspec-bdd from openspec/changes/conversion-matrix/specs/.

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OPENCODE_PROJECT = path.join(HERE, "fixtures", "opencode-project");

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "harnessport-perm-"));
}

function emptyConfig(): HarnessConfig {
  return {
    rules: [], agents: [], skills: [], commands: [],
    mcpServers: [], permissions: [], hooks: [], formatters: [], items: [],
  };
}

function withPermission(
  tool: string,
  pattern: string,
  action: PermissionAction,
): HarnessConfig {
  return { ...emptyConfig(), permissions: [{ tool, pattern, action }] };
}

function withFormatter(glob: string, command: string): HarnessConfig {
  return { ...emptyConfig(), formatters: [{ glob, command }] };
}

function writeOpenCodePermissions(dir: string, permission: unknown): void {
  fs.writeFileSync(
    path.join(dir, "opencode.json"),
    JSON.stringify({ $schema: "https://opencode.ai/config.json", permission }, null, 2),
  );
  fs.writeFileSync(path.join(dir, "AGENTS.md"), "# Rules\n");
}

describe("Requirement: A permission tool name converts in a form the target matches", () => {
  it("An OpenCode ask rule reaches Claude Code in matchable form", () => {
    const src = tmpDir();
    writeOpenCodePermissions(src, { bash: { "git push *": "ask" } });

    const out = tmpDir();
    claudeConverter.export(out, opencodeConverter.import(src), {});
    const settings = fs.readFileSync(
      path.join(out, ".claude", "settings.local.json"),
      "utf-8",
    );
    expect(settings).toContain("Bash(git push *)");
    expect(settings).not.toContain("bash(git push *)");
  });

  it("A bare OpenCode shorthand reaches Claude Code in matchable form", () => {
    const src = tmpDir();
    writeOpenCodePermissions(src, { webfetch: "allow" });

    const out = tmpDir();
    claudeConverter.export(out, opencodeConverter.import(src), {});
    const parsed = JSON.parse(
      fs.readFileSync(path.join(out, ".claude", "settings.local.json"), "utf-8"),
    ) as { permissions: { allow: string[] } };
    expect(parsed.permissions.allow).toContain("WebFetch");
  });

  it("An unmapped tool name is left alone", () => {
    const src = tmpDir();
    writeOpenCodePermissions(src, { external_directory: "allow" });
    const config = opencodeConverter.import(src);
    expect(config.permissions[0].tool).toBe("external_directory");
  });

  // Regression: buildPermissionConfig groups by lowercased tool, so canonical input must still
  // produce the lowercase keys OpenCode expects.
  it("The OpenCode exporter still writes lowercase keys", () => {
    const dir = tmpDir();
    opencodeConverter.export(dir, withPermission("Bash", "npm run:*", "allow"), {});
    const parsed = JSON.parse(
      fs.readFileSync(path.join(dir, "opencode.json"), "utf-8"),
    ) as { permission: Record<string, unknown> };
    expect(Object.keys(parsed.permission)).toContain("bash");
    expect(Object.keys(parsed.permission)).not.toContain("Bash");
  });

  it("Fidelity item names use the canonical tool name", () => {
    const result = opencodeConverter.export(
      tmpDir(),
      opencodeConverter.import(OPENCODE_PROJECT),
      {},
    );
    const names = result.items.filter((i) => i.kind === "permission").map((i) => i.name);
    expect(names.some((n) => n.startsWith("Bash("))).toBe(true);
  });
});

describe("Requirement: A permission OpenCode does not write is not reported exact", () => {
  it("An allowed WebSearch is reported dropped", () => {
    const dir = tmpDir();
    const result = opencodeConverter.export(dir, withPermission("WebSearch", "*", "allow"), {});
    const item = result.items.find((i) => i.kind === "permission");
    expect(item?.name).toBe("WebSearch(*)");
    expect(item?.status).toBe("dropped");

    const parsed = JSON.parse(
      fs.readFileSync(path.join(dir, "opencode.json"), "utf-8"),
    ) as { permission?: Record<string, unknown> };
    expect(Object.keys(parsed.permission ?? {})).not.toContain("websearch");
  });

  it("A denied WebSearch is blocked rather than discarded", () => {
    const result = opencodeConverter.export(
      tmpDir(),
      withPermission("WebSearch", "*", "deny"),
      {},
    );
    expect(result.items.find((i) => i.kind === "permission")?.status).toBe("blocked");
  });

  it("WebFetch is unaffected", () => {
    const dir = tmpDir();
    const result = opencodeConverter.export(dir, withPermission("WebFetch", "*", "allow"), {});
    const parsed = JSON.parse(
      fs.readFileSync(path.join(dir, "opencode.json"), "utf-8"),
    ) as { permission: Record<string, unknown> };
    expect(Object.keys(parsed.permission)).toContain("webfetch");
    expect(result.items.find((i) => i.kind === "permission")?.status).toBe("exact");
  });
});

describe("Requirement: A formatter whose glob Claude Code cannot hold is reported lossy", () => {
  it("An unrecognised formatter command widens the glob and says so", () => {
    const result = claudeConverter.export(
      tmpDir(),
      withFormatter("*.ts", "biome format --write"),
      {},
    );
    const item = result.items.find((i) => i.kind === "formatter");
    expect(item?.status).toBe("lossy");
    expect(item?.reason).toContain("*");
  });

  it("A recognised formatter command round-trips exactly", () => {
    const result = claudeConverter.export(
      tmpDir(),
      withFormatter("*.py", "ruff format"),
      {},
    );
    expect(result.items.find((i) => i.kind === "formatter")?.status).toBe("exact");
  });

  // Regression: only the reported status moves; the emitted hook must be unchanged.
  it("The emitted hook is unchanged", () => {
    const dir = tmpDir();
    claudeConverter.export(dir, withFormatter("*.ts", "biome format --write"), {});
    const parsed = JSON.parse(
      fs.readFileSync(path.join(dir, ".claude", "settings.json"), "utf-8"),
    ) as { hooks: { PostToolUse: Array<{ matcher: string; hooks: Array<{ command: string }> }> } };
    const entry = parsed.hooks.PostToolUse[0];
    expect(entry.matcher).toBe("Edit|Write|MultiEdit");
    expect(entry.hooks[0].command).toBe("biome format --write $FILEPATH");
  });

  it("The widened glob is what re-import actually yields", () => {
    const dir = tmpDir();
    claudeConverter.export(dir, withFormatter("*.ts", "biome format --write"), {});
    expect(claudeConverter.import(dir).formatters[0].glob).toBe("*");
  });
});
