import { describe, it, expect } from "vitest";
import * as path from "node:path";
import * as fs from "node:fs";
import * as os from "node:os";
import * as crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { CONVERTERS } from "../src/matrix.js";
import { inventory, roundTripLoss, divergences } from "../src/compare.js";
import type { FidelityItem, HarnessConfig } from "../src/schema.js";

// Mirrors features/round-trip-verification.feature and features/config-drift-check.feature,
// generated by openspec-bdd from openspec/changes/verify-and-check/specs/.

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.join(HERE, "fixtures");
const CLI = path.resolve(HERE, "..", "dist", "index.js");
const hasBuild = fs.existsSync(CLI);

const FIXTURE_DIRS: Record<string, string> = {
  claude: "sample-project",
  opencode: "opencode-project",
  cursor: "cursor-project",
  windsurf: "windsurf-project",
  copilot: "copilot-project",
  codex: "codex-project",
};

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "harnessport-vc-"));
}

function run(args: string[]) {
  const r = spawnSync("node", [CLI, ...args], { encoding: "utf-8" });
  return { status: r.status, stdout: r.stdout, stderr: r.stderr };
}

/** A hash of every file under a directory, so "unchanged" is checked rather than assumed. */
function treeHash(dir: string): string {
  const hash = crypto.createHash("sha256");
  const walk = (d: string) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true }).sort((a, b) =>
      a.name.localeCompare(b.name),
    )) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else hash.update(path.relative(dir, p)).update(fs.readFileSync(p));
    }
  };
  walk(dir);
  return hash.digest("hex");
}

/** Copy a fixture so a test that (wrongly) wrote into it could not corrupt the real one. */
function copyFixture(name: string): string {
  const dir = tmpDir();
  fs.cpSync(path.join(FIXTURES, FIXTURE_DIRS[name]), dir, { recursive: true });
  return dir;
}

describe("Requirement: verify round-trips a repository without touching it", () => {
  it.runIf(hasBuild)("The inspected directory is left alone", () => {
    const dir = copyFixture("claude");
    const before = treeHash(dir);
    run(["verify", dir, "--from", "claude", "--to", "opencode"]);
    expect(treeHash(dir)).toBe(before);
  });

  it.runIf(hasBuild)("An unknown harness name cannot run", () => {
    const r = run(["verify", copyFixture("claude"), "--from", "nope", "--to", "opencode"]);
    expect(r.status).toBe(1);
  });

  it.runIf(hasBuild)("A directory holding no source config cannot run", () => {
    const r = run(["verify", tmpDir(), "--from", "claude", "--to", "opencode"]);
    expect(r.status).toBe(1);
  });

  it.runIf(hasBuild)("Identical source and target cannot run", () => {
    const r = run(["verify", copyFixture("claude"), "--from", "claude", "--to", "claude"]);
    expect(r.status).toBe(1);
  });
});

describe("Requirement: verify separates accounted-for loss from unaccounted loss", () => {
  function verify(from: string, to: string) {
    const source = CONVERTERS[from].import(path.join(FIXTURES, FIXTURE_DIRS[from]));
    const dir = tmpDir();
    const result = CONVERTERS[to].export(dir, source, {});
    return roundTripLoss(source, CONVERTERS[to].import(dir), result.items);
  }

  it("A dropped permission is accounted for", () => {
    const loss = verify("claude", "cursor");
    expect(loss.accounted.some((l) => l.kind === "permission")).toBe(true);
    expect(loss.unaccounted.filter((l) => l.kind === "permission")).toEqual([]);
  });

  it("A surviving item is not reported as lost", () => {
    const loss = verify("claude", "opencode");
    const all = [...loss.accounted, ...loss.unaccounted];
    expect(all.filter((l) => l.kind === "skill")).toEqual([]);
  });

  it("Lowercase tool naming is not treated as loss", () => {
    const loss = verify("opencode", "claude");
    const all = [...loss.accounted, ...loss.unaccounted];
    expect(all.filter((l) => l.kind === "permission")).toEqual([]);
  });

  it("Unaccounted loss is detected when the report claims exact", () => {
    const source: HarnessConfig = {
      rules: [], agents: [{ name: "ghost", body: "x" }], skills: [], commands: [],
      mcpServers: [], permissions: [], hooks: [], formatters: [], items: [],
    };
    const target: HarnessConfig = { ...source, agents: [] };
    // A report claiming the agent converted fully, while it is absent from the target.
    const items: FidelityItem[] = [
      { phase: "export", kind: "agent", name: "ghost", status: "exact" },
    ];
    const loss = roundTripLoss(source, target, items);
    expect(loss.unaccounted).toEqual([{ kind: "agent", name: "ghost" }]);
    expect(loss.accounted).toEqual([]);
  });
});

describe("Requirement: verify exits 2 only on unaccounted loss", () => {
  it.each([
    ["claude", "opencode"],
    ["claude", "cursor"],
    ["claude", "codex"],
    ["opencode", "claude"],
    ["cursor", "claude"],
    ["codex", "copilot"],
  ])("A lossy but honest conversion passes: %s -> %s", (from, to) => {
    const source = CONVERTERS[from].import(path.join(FIXTURES, FIXTURE_DIRS[from]));
    const dir = tmpDir();
    const result = CONVERTERS[to].export(dir, source, {});
    const loss = roundTripLoss(source, CONVERTERS[to].import(dir), result.items);
    expect(loss.unaccounted).toEqual([]);
  });

  it.runIf(hasBuild)("An honest conversion exits 0 through the CLI", () => {
    const r = run(["verify", copyFixture("claude"), "--from", "claude", "--to", "cursor"]);
    expect(r.status).toBe(0);
  });
});

describe("Requirement: verify reports as JSON on request", () => {
  it.runIf(hasBuild)("JSON output parses and carries both lists", () => {
    const r = run([
      "verify", copyFixture("claude"), "--from", "claude", "--to", "cursor", "--json",
    ]);
    const parsed = JSON.parse(r.stdout) as {
      from: string; to: string;
      accounted: Array<{ kind: string; name: string }>;
      unaccounted: Array<{ kind: string; name: string }>;
    };
    expect(parsed.from).toBe("claude");
    expect(parsed.to).toBe("cursor");
    expect(Array.isArray(parsed.accounted)).toBe(true);
    expect(Array.isArray(parsed.unaccounted)).toBe(true);
    for (const entry of [...parsed.accounted, ...parsed.unaccounted]) {
      expect(entry).toHaveProperty("kind");
      expect(entry).toHaveProperty("name");
    }
  });
});

describe("Requirement: check compares the harness configs present in one repository", () => {
  /** A directory holding two harnesses, so there is something to compare. */
  function twoHarnesses(): string {
    const dir = copyFixture("claude");
    fs.writeFileSync(
      path.join(dir, "AGENTS.md"),
      fs.readFileSync(path.join(dir, ".claude", "CLAUDE.md"), "utf-8"),
    );
    return dir;
  }

  it.runIf(hasBuild)("The inspected directory is left alone", () => {
    const dir = twoHarnesses();
    const before = treeHash(dir);
    run(["check", dir]);
    expect(treeHash(dir)).toBe(before);
  });

  it.runIf(hasBuild)("Fewer than two harnesses is nothing to compare", () => {
    const dir = tmpDir();
    fs.mkdirSync(path.join(dir, ".claude"));
    fs.writeFileSync(path.join(dir, ".claude", "CLAUDE.md"), "# Only claude\n");
    const r = run(["check", dir]);
    expect(r.status).toBe(0);
    expect(`${r.stdout}${r.stderr}`).toMatch(/one harness/i);
  });

  it.runIf(hasBuild)("No configuration at all cannot run", () => {
    expect(run(["check", tmpDir()]).status).toBe(1);
  });
});

describe("Requirement: check reports divergence and fails on it", () => {
  it("A skill present in one harness only is reported", () => {
    const claude = CONVERTERS.claude.import(path.join(FIXTURES, "sample-project"));
    const bare: HarnessConfig = {
      rules: claude.rules, agents: [], skills: [], commands: [],
      mcpServers: [], permissions: [], hooks: [], formatters: [], items: [],
    };
    const found = divergences([
      { harness: "claude", config: claude },
      { harness: "opencode", config: bare },
    ]);
    const skill = found.find((d) => d.kind === "skill" && d.name === "testing");
    expect(skill).toBeDefined();
    expect(skill?.presentIn).toBe("claude");
    expect(skill?.absentFrom).toBe("opencode");
  });

  it("Agreeing configs pass", () => {
    const config = CONVERTERS.claude.import(path.join(FIXTURES, "sample-project"));
    expect(
      divergences([
        { harness: "claude", config },
        { harness: "opencode", config },
      ]),
    ).toEqual([]);
  });

  it("Rules are compared by content, not by file name", () => {
    const text = "# Shared\n\nSame text either way.";
    const base: HarnessConfig = {
      rules: [], agents: [], skills: [], commands: [],
      mcpServers: [], permissions: [], hooks: [], formatters: [], items: [],
    };
    const found = divergences([
      { harness: "claude", config: { ...base, rules: [{ content: text, source: "CLAUDE.md" }] } },
      { harness: "opencode", config: { ...base, rules: [{ content: text, source: "AGENTS.md" }] } },
    ]);
    expect(found.filter((d) => d.kind === "rule")).toEqual([]);
  });

  it.runIf(hasBuild)("Divergence exits 2", () => {
    const dir = copyFixture("claude");
    fs.writeFileSync(path.join(dir, "AGENTS.md"), "# Something else entirely\n");
    expect(run(["check", dir]).status).toBe(2);
  });
});

describe("Requirement: check reports as JSON on request", () => {
  it.runIf(hasBuild)("JSON output parses and carries the detected harnesses", () => {
    const dir = copyFixture("claude");
    fs.writeFileSync(path.join(dir, "AGENTS.md"), "# Rules\n");
    const r = run(["check", dir, "--json"]);
    const parsed = JSON.parse(r.stdout) as { detected: string[] };
    expect(parsed.detected).toContain("claude");
    expect(parsed.detected).toContain("opencode");
  });
});

describe("inventory names things as the fidelity report names them", () => {
  it("permissions are keyed Tool(pattern) and formatters by glob", () => {
    const config: HarnessConfig = {
      rules: [], agents: [], skills: [], commands: [], mcpServers: [],
      permissions: [{ tool: "Bash", pattern: "npm run:*", action: "allow" }],
      hooks: [], formatters: [{ glob: "*.py", command: "ruff format" }], items: [],
    };
    const inv = inventory(config);
    expect(inv.permission).toEqual(["Bash(npm run:*)"]);
    expect(inv.formatter).toEqual(["*.py"]);
  });
});
