# GENERATED by openspec-bdd from openspec/changes/verify-and-check/specs/config-drift-check/spec.md — DO NOT EDIT

Feature: config-drift-check

  # Requirement: check compares the harness configs present in one repository
  # `harnessport check <dir>` SHALL detect every harness configured in `<dir>`, import each, and compare their canonical configs pairwise on the named things each holds. It SHALL write nothing, create nothing, and delete nothing.

  @requirement_check_compares_the_harness_configs_present_in_one_repository
  Scenario: The inspected directory is left alone
    Given a directory holding both claude and opencode configuration
    When running check against it
    Then the set of files under that directory is unchanged
    And their contents are unchanged

  @requirement_check_compares_the_harness_configs_present_in_one_repository
  Scenario: Fewer than two harnesses is nothing to compare
    Given a directory whose only configuration is claude
    When running check against it
    Then the process exits `0`
    And the output states that only one harness was found

  @requirement_check_compares_the_harness_configs_present_in_one_repository
  Scenario: No configuration at all cannot run
    Given an empty directory
    When running check against it
    Then the process exits `1`

  # Requirement: check reports divergence and fails on it
  # Where two detected harnesses hold different sets of named items, each difference SHALL be reported naming the harness that has the item and the harness that does not. The process SHALL exit `2` when any divergence is found and `0` when the detected harnesses agree.

  @requirement_check_reports_divergence_and_fails_on_it
  Scenario: A skill present in one harness only is reported
    Given a directory holding a claude skill named `testing` and an opencode config with no
    When running check against it
    Then the output names `testing` as present in claude and absent from opencode
    And the process exits `2`

  @requirement_check_reports_divergence_and_fails_on_it
  Scenario: Agreeing configs pass
    Given a directory holding claude and opencode configs with the same rules and no other items
    When running check against it
    Then the process exits `0`

  @requirement_check_reports_divergence_and_fails_on_it
  Scenario: Rules are compared by content, not by file name
    Given a directory where claude's `CLAUDE.md` and opencode's `AGENTS.md` hold the same text
    When running check against it
    Then no rule divergence is reported

  # Requirement: check reports as JSON on request
  # With `--json`, the report SHALL be written to stdout as JSON carrying `detected` and `divergences`, each divergence naming `kind`, `name`, `presentIn`, and `absentFrom`. Human-readable output SHALL go to stderr.

  @requirement_check_reports_as_json_on_request
  Scenario: JSON output parses and carries the detected harnesses
    Given a directory holding both claude and opencode configuration
    When running check with `--json`
    Then stdout parses as JSON
    And its `detected` array contains `claude` and `opencode`
