# GENERATED by openspec-bdd from openspec/changes/verify-and-check/specs/round-trip-verification/spec.md — DO NOT EDIT

Feature: round-trip-verification

  # Requirement: verify round-trips a repository without touching it
  # `harnessport verify <dir> --from X --to Y` SHALL import `<dir>` as harness X, export to a directory it creates under the system temporary directory, and re-import that with harness Y. It SHALL NOT create, modify, or delete any file under `<dir>`.

  @requirement_verify_round_trips_a_repository_without_touching_it
  Scenario: The inspected directory is left alone
    Given a claude project directory
    When running verify from claude to opencode against it
    Then the set of files under that directory is unchanged
    And their contents are unchanged

  @requirement_verify_round_trips_a_repository_without_touching_it
  Scenario: An unknown harness name cannot run
    When running verify with `--from` naming a harness that does not exist
    Then the process exits `1`

  @requirement_verify_round_trips_a_repository_without_touching_it
  Scenario: A directory holding no source config cannot run
    Given an empty directory
    When running verify from claude to opencode against it
    Then the process exits `1`

  # Requirement: verify separates accounted-for loss from unaccounted loss
  # Every named item present before the round trip and absent after SHALL be classified. An item named by a fidelity item of the same kind whose status is `lossy`, `dropped`, or `blocked` is **accounted for**. An item with no such fidelity item is **unaccounted**. Permission tool names SHALL be compared case-insensitively, since a harness's own config casing is not a loss.

  @requirement_verify_separates_accounted_for_loss_from_unaccounted_loss
  Scenario: A dropped permission is accounted for
    Given a claude project holding a `Bash` allow permission
    When running verify from claude to cursor
    Then the permission is reported as accounted-for loss
    And it is not reported as unaccounted

  @requirement_verify_separates_accounted_for_loss_from_unaccounted_loss
  Scenario: A surviving item is not reported as lost
    Given a claude project holding a skill named `testing`
    When running verify from claude to opencode
    Then no loss of kind `skill` is reported

  @requirement_verify_separates_accounted_for_loss_from_unaccounted_loss
  Scenario: Lowercase tool naming is not treated as loss
    Given an opencode project holding a `bash` permission
    When running verify from opencode to claude
    Then no loss of kind `permission` is reported for it

  # Requirement: verify exits 2 only on unaccounted loss
  # The process SHALL exit `0` when every loss is accounted for, however much was lost, and exit `2` when any loss is unaccounted. Accounted-for loss is the tool working correctly; unaccounted loss means the fidelity report is wrong.

  @requirement_verify_exits_2_only_on_unaccounted_loss
  Scenario Outline: A lossy but honest conversion passes
    When running verify from `<from>` to `<to>` against that harness's fixture
    Then the process exits `0`

    Examples:
      | from     | to       |
      | claude   | opencode |
      | claude   | cursor   |
      | claude   | codex    |
      | opencode | claude   |
      | cursor   | claude   |
      | codex    | copilot  |

  @requirement_verify_exits_2_only_on_unaccounted_loss
  Scenario: Unaccounted loss fails the run
    Given a conversion whose fidelity report claims `exact` for an item that does not survive
    When running verify
    Then the process exits `2`
    And the item is named in the unaccounted list

  # Requirement: verify reports as JSON on request
  # With `--json`, the report SHALL be written to stdout as JSON carrying `from`, `to`, `accounted`, and `unaccounted`, each loss naming its `kind` and `name`. Human-readable output SHALL go to stderr so stdout stays parseable.

  @requirement_verify_reports_as_json_on_request
  Scenario: JSON output parses and carries both lists
    When running verify from claude to cursor with `--json`
    Then stdout parses as JSON
    And it carries `accounted` and `unaccounted` arrays
    And every entry has a `kind` and a `name`
